Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -149,16 +149,15 @@ stages:
       - task: Bash@3
         inputs:
           targetType: 'inline'
-          script:
-            #failed_tests=`find . -name "Test Result/testresults.trx" -type f | xargs cat | grep -E "outcome=\"Failed\""`
+          script: |
             failed_tests=`cat Test\ Results/testresults.trx|grep failed`
             echo $failed_tests
             echo "hello"
             if [[ -n $failed_tests ]]; then
-              echo "Quality gate failed. There are failed tests."
-              exit 1
+            echo "Quality gate failed. There are failed tests."
+            exit 1
             else
-              echo "Quality gate passed. All tests passed."
+            echo "Quality gate passed. All tests passed."
             fi
           workingDirectory: '$(Agent.TempDirectory)'
 ##########################################################################################################################
